import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Link
        to="/"
        className="inline-flex items-center gap-2 text-brand-600 dark:text-brand-400 hover:text-brand-500 font-medium transition-colors mb-8"
      >
        <ArrowLeft size={20} />
        Back to Budgeity
      </Link>

      <div className="bg-white dark:bg-zinc-900 rounded-3xl shadow-xl border border-slate-200 dark:border-white/10 p-8 sm:p-12">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">
          Privacy Policy
        </h1>
        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 space-y-4">
          <p className="font-medium">
            Last updated: May 19, 2026
            <br />
            Effective date: May 19, 2026
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            1. Introduction & Disclaimer
          </h2>
          <p>
            Welcome to Budgeity. Budgeity is a personal financial budgeting and
            tracking application accessible globally. We are committed to
            protecting your privacy and handling your data with transparency and
            care.
          </p>
          <div className="bg-blue-50 dark:bg-blue-900/30 p-5 rounded-xl border border-blue-100 dark:border-blue-800/50 my-6">
            <p className="text-sm font-medium text-blue-800 dark:text-blue-300 m-0">
              <strong>Important Disclaimer:</strong> Budgeity is a software tool
              designed to help you organize your finances. We are{" "}
              <strong>not</strong> a bank, financial institution, investment
              advisor, legal advisor, or tax advisor. You remain solely
              responsible for your financial decisions. All reports, summaries,
              and analytics generated by Budgeity are provided for informational
              purposes only.
            </p>
          </div>

          <div className="bg-emerald-50 dark:bg-emerald-900/20 p-5 rounded-xl border border-emerald-200 dark:border-emerald-800/50 my-6">
            <h3 className="text-base font-bold text-emerald-900 dark:text-emerald-300 m-0 mb-2 uppercase tracking-wider text-sm">
              Our Core Promise
            </h3>
            <p className="text-sm text-emerald-800 dark:text-emerald-400 m-0">
              <strong>
                Budgeity does NOT sell your personal information or financial
                data.
              </strong>{" "}
              We do not engage in advertising profiling, and we do not use your
              data for third-party marketing without your explicit consent.
            </p>
          </div>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            2. Data We Collect
          </h2>
          <p>
            To provide you with our budgeting services, we collect certain
            information. Most of the financial information we hold is provided
            voluntarily by you when you use the application.
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Identity Data:</strong> Includes your email address,
              username, display name, and profile image.
            </li>
            <li>
              <strong>Financial Data:</strong> Includes information you choose
              to enter, such as transactions, budgets, categories, wallets,
              goals, subscriptions, reports, and data exports.
            </li>
            <li>
              <strong>Technical Data:</strong> Includes your browser type,
              device information, operating system, IP address, timezone
              settings, and basic diagnostic data.
            </li>
            <li>
              <strong>Usage Data:</strong> Includes your feature usage,
              interaction patterns within the app, preferences, and settings
              changes.
            </li>
            <li>
              <strong>Local Device Data:</strong> Includes data stored in your
              local storage, cached preferences, themes, currency settings, and
              app lock preferences.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            3. Legal Basis for Processing
          </h2>
          <p>
            We process your information based on the following legal
            foundations:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Contractual Necessity:</strong> Processing is required to
              provide the core services of Budgeity, such as managing your
              accounts and syncing your financial data.
            </li>
            <li>
              <strong>Consent:</strong> When you have explicitly agreed to let
              us process your data for a specific purpose.
            </li>
            <li>
              <strong>Legitimate Interests:</strong> When processing is
              necessary to improve our services, maintain security, and
              troubleshoot issues, provided these interests do not override your
              fundamental privacy rights.
            </li>
            <li>
              <strong>Legal Obligations:</strong> When we are required to
              process data to comply with applicable laws or regulations.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            4. Third-Party Services & Infrastructure
          </h2>
          <p>
            Budgeity relies on trusted third-party infrastructure providers to
            deliver a reliable experience. These may include services for user
            authentication, cloud databases, and hosting infrastructure (such as
            Firebase). These providers may process information necessary to
            deliver their services and maintain their own privacy and security
            practices.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            5. International Data Transfers
          </h2>
          <p>
            Because Budgeity operates globally, your information may be
            processed and stored on servers located outside of your home country
            or jurisdiction. Where this occurs, we ensure that appropriate
            safeguards are applied to protect your personal data in accordance
            with applicable privacy laws.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            6. Data Retention
          </h2>
          <p>
            We retain your personal and financial data for as long as your
            account remains active. Our goal is to provide continuous access to
            your historical financial information. When an account is deleted,
            the associated account and financial data are slated for removal.
            Please note that data removal may take a specific timeline to
            complete across our active systems, and portions of data may
            temporarily persist in encrypted system backups until those backups
            are routinely rotated and overwritten.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            7. Account Deletion & Shared Spaces
          </h2>
          <p>
            Deleting your account will remove your personal profile and the
            financial data you solely own. However, if you participate in shared
            spaces or household financial tracking, some records of transactions
            or budgets that you contributed to may remain visible to the other
            active members of those shared spaces to preserve the integrity of
            their financial histories.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            8. Offline Storage & PWA Behaviour
          </h2>
          <p>
            Budgeity functions as a Progressive Web Application (PWA). To enable
            offline functionality, faster loading times, and a smoother
            experience, the application may cache certain information (including
            financial data and user preferences) locally on your device. This
            local data will persist on your device until it is cleared through
            your browser or device settings.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            9. App Lock & Local Security
          </h2>
          <p>
            If you enable local security features such as an App Lock (PIN,
            pattern, or biometric authentication), certain security preferences
            or settings may be stored locally on your device. These features are
            designed to increase convenience and provide a layer of local
            privacy, but they do not replace the primary security of your
            account credentials.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            10. Security Measures
          </h2>
          <p>
            We implement reasonable safeguards designed to protect your personal
            information against unauthorized access, loss, or alteration. These
            measures include encryption in transit, secure authentication
            protections, strict access controls, and database security rules to
            restrict data access. While we strive to protect your data, no
            system is entirely immune to risks, and we encourage you to use
            strong passwords and protect your account credentials.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            11. Cookies & Tracking
          </h2>
          <p>
            Budgeity uses only essential cookies and local storage mechanisms
            required for the application to function properly (such as
            maintaining your session, remembering your settings, and enabling
            offline mode). We do not use advertising profiling or third-party
            marketing tracking mechanisms without your explicit consent.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            12. Children’s Privacy
          </h2>
          <p>
            Budgeity is not intended for use by children below the legally
            applicable age of digital consent in their jurisdiction, unless
            explicit permission is provided by a parent or guardian where
            required by law. If we discover that an underage user has created an
            account without proper authorization, we will take steps to securely
            delete the account and associated data.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            13. Breach Notification
          </h2>
          <p>
            In the event of a significant data breach that compromises the
            security of your personal information, we will inform affected users
            and relevant regulatory authorities as required by applicable law.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            14. Your Privacy Rights
          </h2>
          <p>
            Depending on your jurisdiction, you may have specific rights
            regarding your personal data. These may include the right to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Request <strong>access</strong> to your personal data.
            </li>
            <li>
              Request <strong>correction</strong> of inaccurate or incomplete
              data.
            </li>
            <li>
              Request <strong>deletion</strong> of your personal data.
            </li>
            <li>
              Request <strong>restriction</strong> of how we process your data.
            </li>
            <li>
              Request <strong>portability</strong> of your data to another
              service, or request a copy/export of your personal data where
              applicable.
            </li>
            <li>
              <strong>Withdraw consent</strong> at any time, where processing is
              based on your consent.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
