import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const TermsOfService: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <Link
        to="/"
        className="inline-flex items-center gap-2 text-brand-600 dark:text-brand-400 hover:text-brand-500 font-medium transition-colors mb-8"
      >
        <ArrowLeft size={20} />
        Back to Budgeity
      </Link>

      <div className="bg-white dark:bg-zinc-900 rounded-3xl shadow-xl border border-slate-200 dark:border-white/10 p-8 sm:p-12">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-6">
          Terms of Service
        </h1>
        <div className="prose prose-slate dark:prose-invert max-w-none text-slate-600 dark:text-slate-300 space-y-4">
          <p className="font-medium">Last updated: May 19, 2026</p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            1. Agreement to Terms
          </h2>
          <p>
            Welcome to Budgeity. By accessing or using the Budgeity application
            from any location, you agree to be bound by these Terms of Service.
            If you do not agree with any of these terms, please discontinue use
            of the service immediately.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            2. Financial Disclaimer (Critical)
          </h2>
          <div className="bg-amber-50 dark:bg-amber-900/30 p-5 rounded-xl border border-amber-200 dark:border-amber-800/50 my-6">
            <p className="text-sm font-medium text-amber-900 dark:text-amber-200 m-0">
              <strong>
                Budgeity is a software tool for budgeting and financial
                tracking.
              </strong>{" "}
              We are <strong>not</strong> a bank, financial institution,
              investment advisor, accountant, tax advisor, or legal advisor. All
              reports, summaries, analytics, exports, and budgeting insights
              generated by the application are for informational purposes only.
              You remain solely responsible for your financial decisions. We do
              not guarantee any specific financial outcomes resulting from the
              use of our service.
            </p>
          </div>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            3. Eligibility & Minimum Age
          </h2>
          <p>
            You must satisfy the applicable legal age requirements in your
            jurisdiction to use Budgeity. If you are below the required age, you
            may only use the application with explicit permission and
            supervision from a parent or legal guardian.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            4. Account Responsibilities
          </h2>
          <p>
            To use certain features, you must create an account. You agree to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Maintain accurate and current account information.</li>
            <li>Protect your login credentials.</li>
            <li>Promptly update your account details when necessary.</li>
            <li>Report any unauthorized access to us immediately.</li>
          </ul>
          <p className="mt-4">
            You are responsible for all activity that occurs under your account,
            except where required by applicable law.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            5. App Lock & Security Features
          </h2>
          <p>
            Budgeity may offer local security features such as PINs, patterns,
            or biometric app locks. While these features improve convenience and
            local security, they do not guarantee the prevention of unauthorized
            access to your device. You remain responsible for the physical
            security of your devices.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            6. Acceptable Use Policy
          </h2>
          <p>
            You agree to use Budgeity responsibly. You must not use the service
            for any:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Unlawful or fraudulent activity.</li>
            <li>Malicious behaviour or abuse of the application.</li>
            <li>Automated data extraction or scraping.</li>
            <li>Attempts to bypass or compromise security systems.</li>
            <li>
              Distribution of malware or automated exploitation of the service.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            7. Shared Accounts & Household Rules
          </h2>
          <p>
            If you participate in shared financial spaces or households within
            the app, you are entirely responsible for deciding whom you share
            your financial data with. Budgeity is not liable for any
            unauthorized disclosures or disputes caused by your decision to
            share information with other users.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            8. Data Ownership
          </h2>
          <p>
            You retain full ownership of the financial information and data you
            submit to Budgeity. By using the service, you grant Budgeity the
            necessary permissions to process, securely store, and display this
            data solely for the purpose of operating and providing the
            application to you.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            9. Reports & Export Disclaimer
          </h2>
          <p>
            Any generated reports, PDF documents, analytics, data exports, or
            financial summaries rely entirely on the information you provide.
            The accuracy of these outputs depends on the accuracy of your
            entered data. Budgeity does not guarantee the completeness or
            absolute correctness of these generated reports.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            10. Currency & Exchange Rates
          </h2>
          <p>
            Budgeity supports multiple global currencies. Please be aware that
            any displayed exchange rates may experience lag, differ from
            official financial institutions, and deviate from real-time market
            rates. These rates are provided for estimation purposes and are not
            suitable for financial trading decisions.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            11. Service Availability
          </h2>
          <p>
            We strive to keep Budgeity accessible, but we do not promise
            uninterrupted access. The services may experience occasional
            downtime, planned maintenance, unexpected outages, or other
            interruptions.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            12. Third-Party Services
          </h2>
          <p>
            Budgeity relies on trusted external providers for critical
            infrastructure, including user authentication, cloud databases, and
            hosting services. While we carefully select our partners,
            interruptions or issues originating from these third-party services
            may temporarily affect Budgeity's functionality.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            13. Feature Changes & Discontinuation
          </h2>
          <p>
            To continually improve our platform, features within Budgeity may
            evolve, change, or be discontinued over time. We will make
            reasonable efforts to provide advance notice for major feature
            changes or deprecations.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            14. Beta & Experimental Features
          </h2>
          <p>
            We may occasionally offer features marked as "Beta" or
            "Experimental". These features are still in development, meaning
            unexpected issues or bugs may occur. By choosing to use these
            features, you accept the associated risks.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            15. Limitation of Liability
          </h2>
          <p>
            The service is provided on an "AS IS" and "AS AVAILABLE" basis. To
            the maximum extent permitted by law, Budgeity and its operators
            shall not be liable for any indirect, incidental, or consequential
            losses, including but not limited to:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Losses arising from personal financial decisions.</li>
            <li>Lost profits or expected savings.</li>
            <li>
              Losses resulting from service downtime or data unavailability.
            </li>
          </ul>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            16. Indemnification
          </h2>
          <p>
            You agree to indemnify and hold harmless Budgeity, its developers,
            and affiliates from any claims, damages, or expenses resulting from
            your misuse of the service or your violation of these Terms of
            Service.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            17. Termination
          </h2>
          <p>
            We reserve the right to suspend or terminate your account if you
            violate these Terms, engage in abuse, pose a security risk, or for
            legitimate legal reasons or protection of service integrity. You may
            also delete your account at any time through the application
            settings. Upon deletion, your data will be handled in accordance
            with our Privacy Policy.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            18. Intellectual Property
          </h2>
          <p>
            While you own your uploaded financial data, Budgeity retains all
            ownership and intellectual property rights to the application's
            branding, logos, interface, software, and design. You may not copy,
            modify, or distribute any part of the application without explicit
            permission.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            19. Force Majeure
          </h2>
          <p>
            Budgeity shall not be liable for any failure or delay in performance
            caused by circumstances beyond our reasonable control, including
            natural disasters, internet outages, government restrictions, and
            infrastructure failures.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-white mt-8 mb-4">
            20. Governing Law
          </h2>
          <p>
            These Terms shall be governed by the laws of India, unless
            overriding local consumer protection laws in your region apply.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
